### ISSUE TITLE
Details?

### ISSUE THREAD

**Issue by JuanPabloPearce** [TheNamlessGuy/browser-tab-grouper#2]
So I am looking for a group tab extension for Firefox that works EXACTLY like the Microsoft Edge tab groups (the built in one). This one is pretty self explanatory until you look at all the other extensions with similar names and see their idea of grouped tabs is way different than Microsoft Edge. 

Could you explain how this extension works and maybe include screenshots?

**Comment by TheNamlessGuy** [comment]
Hi! I added some info to the [README](https://github.com/TheNamlessGuy/browser-tab-grouper/blob/main/README.md)

**Comment by JuanPabloPearce** [comment]
Very nice, thank you!
