### ISSUE TITLE
Mouse gestures don't work on the Group tab.

### ISSUE THREAD

**Issue by cnpym-github** [TheNamlessGuy/browser-tab-grouper#6]
It's like a speed bump for mouse control.

**Comment by TheNamlessGuy** [comment]
I can't find that mouse gestures are officially implemented in firefox, so I'm guessing you're referring to one of the dozens of plugins that do this. Unfortunately, that mostly depends on how that plugin is implemented, and AFAIK it has nothing to do with this plugin.

If you mention what gesture plugin you're using I can look into if it's a quick fix.

**Comment by cnpym-github** [comment]
Sorry, I didn't specify the name of the FF extension.
I use https://addons.mozilla.org/en-US/firefox/addon/gesturefy

**Comment by TheNamlessGuy** [comment]
I opened [an issue](https://github.com/Robbendebiene/Gesturefy/issues/728) for their plugin, please follow that for further updates.
