### ISSUE TITLE
Overwriting "root tab" of tab group using Firefox's history feature causes the extension to freak out

### ISSUE THREAD

**Issue by ridiche34** [TheNamlessGuy/browser-tab-grouper#7]
Steps to reproduce:

1. Create a new tab group
2. Select the "root tab"
3. Press Ctrl+H
4. Click on a random webpage
5. The tab group starts acting really weirdly

**Comment by TheNamlessGuy** [comment]
Oh yeah, good catch. The plugin doesn't handle redirecting away from the plugin page at all. Never thought to try

**Comment by TheNamlessGuy** [comment]
This should be fixed in v0.3.1, releasing whenever Firefox decides my upload is OK
