### ISSUE TITLE
Can't add tabs in old groups.

### ISSUE THREAD

**Issue by Tez-byte** [TheNamlessGuy/browser-tab-grouper#9]
My laptop reloaded not so long ago and all windows get closed. I restored previous session but when I tried to add tab in preexistent group there weren't any in drop-down menu (I tried to add screenshot). 
I can create new groups and add tabs in them. I also can axcess tabs in older groups and change their settings.
![изображение](https://github.com/user-attachments/assets/0f6d9392-d32a-4b61-816b-b5bd9123ffe2)

**Comment by TheNamlessGuy** [comment]
That's strange. I'll take a look

**Comment by TheNamlessGuy** [comment]
This should be fixed in the new release (0.4.0). You may have to close and reopen any windows currently facing this issue.
